---
title: "lending club"
author: "aki"
date: "11/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
data <- read_csv('~/loan.csv')
totalkeep=c("application_type","acc_now_delinq","chargeoff_within_12_mths","delinq_amnt","loan_amnt","funded_amnt","term","int_rate","grade","sub_grade","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","purpose","addr_state","delinq_2yrs","total_acc","pct_tl_nvr_dlq")
newdatloan= data%>% select(totalkeep)

cleandatloan <- newdatloan %>%
mutate(home_status= ifelse(home_ownership %in% c("ANY","NONE","OTHER"),"Unknown",home_ownership)) 
  
cleandatloan$loan_status[cleandatloan$loan_status=="Does not meet the credit policy. Status:Fully Paid"]="Fully Paid"

cleandatloan <- cleandatloan %>%  filter(loan_status!="Current") %>% mutate(label= ifelse(loan_status=="Fully Paid",1,0),      pastdelinq=ifelse(delinq_2yrs==0,0,ifelse(delinq_2yrs==1,1,2)),
                                         nowdelinq=ifelse(acc_now_delinq==0,0,1),
                                         chargedoffrecord=ifelse(chargeoff_within_12_mths==0,0,1))

loanData <- readRDS("loanData (1).rds")
set.seed(123)
totaldataset=sample(loanData)
traindataset=data[1:1695501,]
testdataset=data[1695502:2260668,]


```
